packages:
  - apps/*
  - packages/*
  - tooling/*

catalog:
  eslint: ^9.12.0
  prettier: ^3.3.3
  tailwindcss: ^3.4.14
  typescript: ^5.6.3
  zod: ^3.23.8

catalogs:
  next15:
    next: ^15.0.0
    react: ^19.0.0
    react-dom: ^19.0.0
